### ISSUE TITLE
build android client failed

### ISSUE THREAD

**Issue by cloudending** [alvr-org/ALVR#1112]
My environment:
Android Studio 2021.1.1
Windows 10
ALVR v18.2.3
rustup 1.24.3
rustc 1.62
I use the following command to build android client:
```
cargo xtask build-android-deps
cargo xtask build-client --release
```
But it outputs some error:
```
    Finished dev [unoptimized + debuginfo] target(s) in 5.27s
     Running `target\debug\alvr_xtask.exe build-client --release`

> gradlew.bat assembleOculusQuestStablerelease
Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be reused, use --status for details

> Task :app:cargoBuildArm64
warning: unused import: `alvr_common::ALVR_VERSION`
 --> alvr\session\src\settings.rs:1:5
  |
1 | use alvr_common::ALVR_VERSION;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `DictionaryDefault`
 --> alvr\session\src\settings.rs:4:23
  |
4 | use settings_schema::{DictionaryDefault, EntryData, SettingsSchema, Switch, SwitchDefault};
  |                       ^^^^^^^^^^^^^^^^^

warning: `alvr_session` (lib) generated 2 warnings
warning: D:\Project\ALVR1\alvr\client\android\app/src/main/cpp\ovr_context.cpp:543:18: warning: unused variable 'trackingRaw' [-Wunused-variable]
warning:     ovrTracking2 trackingRaw = vrapi_GetPredictedTracking2(g_ctx.Ovr, 0.);
warning:                  ^
warning: 1 warning generated.
warning: field is never read: `stream_id`
   --> alvr\sockets\src\stream_socket\mod.rs:168:5
    |
168 |     stream_id: StreamId,
    |     ^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: `alvr_sockets` (lib) generated 1 warning
   Compiling alvr_client v18.2.3 (D:\Project\ALVR1\alvr\client)
warning: unused imports: `Quat`, `Vec3`, `log`
  --> alvr\client\src\connection.rs:9:12
   |
9  |     glam::{Quat, Vec2, Vec3},
   |            ^^^^        ^^^^
10 |     log,
   |     ^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `ptr`, `slice`
  --> alvr\client\src\connection.rs:29:18
   |
29 |     future, mem, ptr, slice,
   |                  ^^^  ^^^^^

warning: unused import: `AUDIO`
 --> alvr\client\src\audio.rs:3:50
  |
3 | use alvr_sockets::{StreamReceiver, StreamSender, AUDIO};
  |                                                  ^^^^^

warning: unused import: `ptr`
  --> alvr\client\src\lib.rs:32:5
   |
32 |     ptr, slice,
   |     ^^^

error: linking with `D:\Project\ALVR1\alvr\client\android\build\linker-wrapper\linker-wrapper.bat` failed: exit code: 1
  |
  = note: "cmd" "/c" "D:\\Project\\ALVR1\\alvr\\client\\android\\build\\linker-wrapper\\linker-wrapper.bat" "-Wl,--version-script=C:\\Users\\LIAOJI~1\\AppData\\Local\\Temp\\rustcHAeU03\\list" "C:\\Users\\LIAOJI~1\\AppData\\Local\\Temp\\rustcHAeU03\\symbols.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.0.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.1.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.10.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.11.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.12.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.13.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.14.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.15.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.2.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.3.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.4.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.5.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.6.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.7.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.8.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.alvr_client.02fc082a-cgu.9.rcgu.o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\alvr_client.1r9s53zzkr6szrx1.rcgu.o" "-Wl,--as-needed" "-L" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps" "-L" "D:\\Project\\ALVR1\\target\\release\\deps" "-L" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\build\\alvr_client-80e337dd83ec8b1b\\out" "-L" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\build\\alvr_client-80e337dd83ec8b1b\\out" "-L" "D:\\Project\\ALVR1\\alvr\\client\\android/app/src/main/jniLibs/arm64-v8a" "-L" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\build\\ring-6321a5991baf4eb0\\out" "-L" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\build\\oboe-sys-742c48080d2d65d1\\out\\library" "-L" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\build\\oboe-sys-742c48080d2d65d1\\out\\library" "-L" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\build\\minimp3-sys-06ca6f46d8b9f741\\out" "-L" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib" "-Wl,-Bstatic" "-lbindings" "-Wl,-Bdynamic" "-lc++_static" "-Wl,-Bstatic" "-lbindings_rs_c" "-Wl,-Bdynamic" "-llog" "-lvrapi" "-lGLESv3" "-lEGL" "-landroid" "-lOpenSLES" "-lovrplatformloader" "-Wl,-Bstatic" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libalvr_audio-958a57f707d388cf.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\librodio-2e168d26f81f954e.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libhound-cda8086425339c55.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\liblewton-cb9120e6268c23fe.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libogg-3780788c322fd7af.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libtinyvec-c1b920e7979f8c33.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libtinyvec_macros-703471e2ec442a02.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libbyteorder-c27fe047ce3cdcbb.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libminimp3-941aed1f3d6fc663.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libslice_deque-d34809aa4ee00f7e.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libminimp3_sys-e4d151301d2e450e.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libclaxon-4bc4990a90a69a2d.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libcpal-d0d546bf736c10b1.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libandroid_logger-905da871703ef2eb.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libenv_logger-652c4af5767350b5.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libregex-145ab0bfbd98177a.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libaho_corasick-3c4b90bf3987c17f.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libregex_syntax-34f52d97c283d139.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libandroid_log_sys-7918d319f9a3eefc.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libparking_lot-f160121ee7265bfc.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libparking_lot_core-3f8e61802063efd7.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\liboboe-a5d9f1e32472eaf5.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libndk_glue-6436b35673211e1e.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libndk_context-abedcc72f69c3cc6.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libndk-66ad0384fad160ca.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libndk_sys-cd52e5fe0acea4e4.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libbitflags-0be4b7b93290f973.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libnum_enum-db44f62a8b4ba0ca.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\liboboe_sys-1c418315dca01f81.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libnum_traits-439ecb94c4593897.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libjni-dd25e099987adb8c.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libcesu8-672d54d4ca052ddf.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libcombine-09b90952881a83ab.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libthiserror-3d40c3074e512291.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libjni_sys-ecddeb41ce688093.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libalvr_sockets-c35def401bd51f1f.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\librcgen-bc45dd559f53bb5f.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libring-22243ad905d2441d.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libspin-cf9992d76a2da9a2.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libuntrusted-1a0d7bdfef199313.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libonce_cell-717dbfd259640d33.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libpem-f5a267e5bc6778c8.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libbase64-af95b900a7e1bd48.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libyasna-ab7ca29df6ed1c8c.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libtime-20f7aa2bc014e438.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libbincode-fc00d1c03cff1e6d.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libnonzero_ext-8ea7c66eeaaae00f.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libgovernor-25fcf76f9515b44f.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libquanta-da4a2cda800882eb.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libdashmap-73834c361a961617.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libparking_lot-2c3ce6f2807e6896.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libparking_lot_core-c37486e114357f8e.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libsmallvec-d0cf5a05faa0a3c8.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\liblock_api-797d9a0feb2a50d8.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libscopeguard-63df08b7b83c7476.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libinstant-409b32c11f471122.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libfutures_timer-d3f859e64fd8b01e.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libnonzero_ext-46dad95a52f4b364.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\librand-050ddbfca24861c5.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\librand_chacha-1b2f75f35b99777f.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libppv_lite86-445c4567489a70d0.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\librand_core-a0809278868bdf13.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libgetrandom-20531e96cc3d74d8.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libno_std_compat-d208298a1a4d8f9e.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libtokio_util-29b13269fa8e483e.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libtokio-64fcf3ec25aaa3f7.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libnum_cpus-94fb57511a24b227.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libsocket2-f03f35c153b6929b.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libmio-1b15d47f1c631d0b.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libfutures-bb27ca8bcb60730a.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libfutures_executor-5e031cfe3f804cd5.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libfutures_util-d8161f59d8cd1771.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libfutures_io-4a4cb252f5a40baf.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libslab-fe705aa94b9d74d8.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libfutures_channel-fd205978e25bdce6.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libpin_project_lite-50ceb20323b03c67.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libfutures_sink-7f43fdd40274a39b.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libfutures_task-8c0629dbb0a9a82a.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libpin_utils-fe20726bc7b04599.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libfutures_core-3a304e306a26fa64.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libbytes-dfacb8c1227ee255.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libalvr_session-7e53a64588803c7a.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libsettings_schema-10e9ec2c009d2797.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libserde_json-678fca112aef82d9.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libryu-8fe94198cc056d22.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libitoa-8816c0be6ba72f45.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libbytemuck-6f481941055ab7cf.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libalvr_common-7cc84693c0d13cbe.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libbacktrace-1cf40bed337bf9c9.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libminiz_oxide-2cf5420fe2cc103e.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libadler-f236c771228a9a12.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libobject-482c520c89b45f16.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libmemchr-94133d33115aa002.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\liblibc-afbfb6d71312a1c1.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libaddr2line-c834fb587065b5f9.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libgimli-39cb03a5a6cd14e4.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\librustc_demangle-72b7564067843120.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libsemver-0df0fbb33b77261d.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\liblog-c552d95642a15142.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libcfg_if-0e196ba13b18c089.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\liblazy_static-57916590bd2012c2.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libglam-368b6781f573a59c.rlib" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libserde-2d70ef9f46fe3163.rlib" "-Wl,--start-group" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libstd-fbdf92ba3f92591d.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libpanic_unwind-a56ac574867e034e.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libobject-c9ae0716c104b8d7.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libmemchr-c3fa18b8c3edf43b.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libaddr2line-fa1fc3a812a80055.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libgimli-50ed162c3b155b9a.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\librustc_demangle-7daadb73dd068a90.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libstd_detect-62a19f039288a20e.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libhashbrown-39b20c392dd0d97b.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libminiz_oxide-195fd6674646c0c6.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libadler-49e6c71fac171787.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\librustc_std_workspace_alloc-7c24439fca69b2ea.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libunwind-cf716ea00340f1ee.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libcfg_if-b3520f02a9bc5297.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\liblibc-cae1fe7e1feef9f9.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\liballoc-f794e6c09bd2128a.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\librustc_std_workspace_core-6054af3a685a634c.rlib" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libcore-ffa17c4bf270a09b.rlib" "-Wl,--end-group" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libcompiler_builtins-72f56d80d146f533.rlib" "-Wl,-Bdynamic" "-llog" "-landroid" "-lc++_static" "-llog" "-lOpenSLES" "-ldl" "-llog" "-lgcc" "-ldl" "-lc" "-lm" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "D:\\Rust\\Rustup_home\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib" "-o" "D:\\Project\\ALVR1\\target\\aarch64-linux-android\\release\\deps\\libalvr_client.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: Non-UTF-8 output: \xcf\xb5\xcd\xb3\xd5\xd2\xb2\xbb\xb5\xbd\xce\xc4\xbc\xfe D:\\Project\\ALVR1\\python_bin_reldir.txt\xa1\xa3\r\n\'\"D:\\Project\\ALVR1\\\\python.exe\"\' \xb2\xbb\xca\xc7\xc4\xda\xb2\xbf\xbb\xf2\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\xa3\xac\xd2\xb2\xb2\xbb\xca\xc7\xbf\xc9\xd4\xcb\xd0\xd0\xb5\xc4\xb3\xcc\xd0\xf2\r\n\xbb\xf2\xc5\xfa\xb4\xa6\xc0\xed\xce\xc4\xbc\xfe\xa1\xa3\r\n\r\nD:\\Project\\ALVR1>\"python\" \"D:\\Project\\ALVR1\\alvr\\client\\android\\build\\linker-wrapper\\linker-wrapper.py\" @C:\\Users\\LIAOJI~1\\AppData\\Local\\Temp\\rustcHAeU03\\linker-arguments \r\n

warning: `alvr_client` (lib) generated 4 warnings
The following warnings were emitted during compilation:

warning: D:\Project\ALVR1\alvr\client\android\app/src/main/cpp\ovr_context.cpp:543:18: warning: unused variable 'trackingRaw' [-Wunused-variable]
warning:     ovrTracking2 trackingRaw = vrapi_GetPredictedTracking2(g_ctx.Ovr, 0.);
warning:                  ^
warning: 1 warning generated.

error: could not compile `alvr_client` due to previous error; 4 warnings emitted

> Task :app:cargoBuildArm64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cargoBuildArm64'.
> Process 'command 'cargo'' finished with non-zero exit value 101

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 12s
3 actionable tasks: 3 executed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StringError("Command failed: ")', alvr\xtask\src\main.rs:317:59
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\result.rs:1785
   3: enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error>,alloc::alloc::Global> >, 1, 18446744073709551615, Err>::unwrap<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error>,alloc::alloc::Global> >
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\result.rs:1078
   4: alvr_xtask::build_client
             at D:\Project\ALVR1\alvr\xtask\src\main.rs:317
   5: alvr_xtask::main
             at D:\Project\ALVR1\alvr\xtask\src\main.rs:414
   6: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\alvr_xtask.exe build-client --release` (exit code: 101)
```
I have no idea of this error. please help me. Or which version of android studio and rustup can be used to build android client?

**Comment by zarik5** [comment]
The v18 branch requires Android Studio 2020.3.1 (Artic fox) or prior. This restriction in lifted in the master branch and soon on the v19 branch.

**Comment by zarik5** [comment]
You should clean the project before trying again. I suggest you to clone again.

**Comment by cloudending** [comment]
It works after I change python version to 3.10!!
