### ISSUE TITLE
Help! Windows <ScreenGrab.h> Problem Orz

### ISSUE THREAD

**Issue by waterthree3** [alvr-org/ALVR#1130]
I want to get the video stream of steam, and I want to use the ScreenGrab-SaveDDSTextureToFile function in the previous ALVR-2.3.1 version, but when I add ScreenGrab11.h and ScreenGrab11.cpp from [DirectXTex](https://github.com/microsoft/DirectXTex) to the project, the compilation error is as follows:

```
= note: Non-UTF-8 output:   \xd5\xfd\xd4\xda\xb4\xb4\xbd\xa8\xbf\xe2 D:\\cloudvr\\ALVR_16.0_APK\\ALVR-16.0.0\\ALVR-16.0.0\\target\\release\\deps\\alvr_server.dll.lib \xba\xcd\xb6\xd4\xcf\xf3 D:\\cloudvr\\ALVR_16.0_APK\\ALVR-16.0.0\\ALVR-16.0.0\\target\\release\\deps\\alvr_server.dll.exp\r\nbindings.lib(VideoEncoderNVENC.o) : 
error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 \"long __cdecl DirectX::SaveDDSTextureToFile(struct ID3D11DeviceContext *,struct ID3D11Resource *,wchar_t const *)\" (?SaveDDSTextureToFile@DirectX@@YAJPEAUID3D11DeviceContext@@PEAUID3D11Resource@@PEB_W@Z)\xa3\xac\xba\xaf\xca\xfd \"public: virtual void __cdecl VideoEncoderNVENC::Transmit(struct ID3D11Texture2D *,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,bool)\" (?Transmit@VideoEncoderNVENC@@UEAAXPEAUID3D11Texture2D@@_K111_N@Z) \xd6\xd0\xd2\xfd\xd3\xc3\xc1\xcb\xb8\xc3\xb7\xfb\xba\xc5\r\nD:\\cloudvr\\ALVR_16.0_APK\\ALVR-16.0.0\\ALVR-16.0.0\\target\\release\\deps\\alvr_server.dll : 
fatal error LNK1120: 1 \xb8\xf6\xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\r\n

warning: `alvr_server` (lib) generated 4 warnings
error: could not compile `alvr_server` due to previous error; 4 warnings emitted
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Command failed: "', alvr\xtask\src\main.rs:206:10
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\result.rs:1785
   3: enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error>,alloc::alloc::Global> >, 1, 18446744073709551615, Err>::unwrap<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error>,alloc::alloc::Global> >
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\result.rs:1078
   4: alvr_xtask::build_server
             at .\alvr\xtask\src\main.rs:198
   5: alvr_xtask::main
             at .\alvr\xtask\src\main.rs:567
   6: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\alvr_xtask.exe build-server --release` (exit code: 101)
```

- Version: ALVR-16.0.0
- OS: WIN11

In addition, I found that the initial version included ScreenGrab, but it was quickly removed. Is it useless or there is a better way?

**Comment by zarik5** [comment]
You can screen capture the VR gameplay with OpenVR input plugin for OBS.

**Comment by waterthree3** [comment]
Ok,thanks
