### ISSUE TITLE
Alvr-Server: Build From Source Error

### ISSUE THREAD

**Issue by Damian96gz** [alvr-org/ALVR#1149]
Hi I am trying to follow the document here: https://github.com/alvr-org/ALVR/wiki/Building-From-Source

However, when I am running _"cargo xtask build-server --release"_ , it gave me the following error(I only posted the error part of the code here since it's too long):

Can anyone help me with this problem? I am running it on a Windows 10 Machine. Thanks!

```
$ cargo build --release
   Compiling alvr_server v19.0.0-dev00 (C:\Users\85463\OneDrive\Desktop\vrdecode\alvr2\ALVR\alvr\server)
error: failed to run custom build command for `alvr_server v19.0.0-dev00 (C:\Users\85463\OneDrive\Desktop\vrdecode\alvr2\ALVR\alvr\server)`

Caused by:
  process didn't exit successfully: `C:\Users\85463\OneDrive\Desktop\vrdecode\alvr2\ALVR\target\release\build\alvr_server-a409f376077abc2a\build-script-build` (exit code: 1)
  --- stdout
  ......
  exit code: 0
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "cpp/openvr/headers" "-I" "cpp" "-W4" "/std:c++17" "/permissive-" "-DNOMINMAX" "-D_WINSOCKAPI_" "-D_MBCS" "-D_MT" "-FoC:\\Users\\85463\\OneDrive\\Desktop\\vrdecode\\alvr2\\ALVR\\target\\release\\build\\alvr_server-36bb51e4fcde8315\\out\\cpp/platform/win32\\amf\\common\\Windows\\ThreadWindows.o" "-c" "cpp/platform/win32\\amf\\common\\Windows\\ThreadWindows.cpp"
  ThreadWindows.cpp
  exit code: 0
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "cpp/openvr/headers" "-I" "cpp" "-W4" "/std:c++17" "/permissive-" "-DNOMINMAX" "-D_WINSOCKAPI_" "-D_MBCS" "-D_MT" "-FoC:\\Users\\85463\\OneDrive\\Desktop\\vrdecode\\alvr2\\ALVR\\target\\release\\build\\alvr_server-36bb51e4fcde8315\\out\\cpp/platform/win32\\CEncoder.o" "-c" "cpp/platform/win32\\CEncoder.cpp"
  C:\Users\85463\OneDrive\Desktop\vrdecode\alvr2\ALVR\alvr\server\cpp\platform\win32\amf\common\../include/core/Platform.h(394): warning C4201: nonstandard extension used: nameless struct/union
  CEncoder.cpp
  exit code: 0
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "cpp/openvr/headers" "-I" "cpp" "-W4" "/std:c++17" "/permissive-" "-DNOMINMAX" "-D_WINSOCKAPI_" "-D_MBCS" "-D_MT" "-FoC:\\Users\\85463\\OneDrive\\Desktop\\vrdecode\\alvr2\\ALVR\\target\\release\\build\\alvr_server-36bb51e4fcde8315\\out\\cpp/platform/win32\\d3d-render-utils\\RenderPipeline.o" "-c" "cpp/platform/win32\\d3d-render-utils\\RenderPipeline.cpp"
  RenderPipeline.cpp
  C:\Users\85463\OneDrive\Desktop\vrdecode\alvr2\ALVR\alvr\server\cpp\alvr_server\Statistics.h(47): warning C4244: '=': conversion from 'double' to 'uint64_t', possible loss of data
  C:\Users\85463\OneDrive\Desktop\vrdecode\alvr2\ALVR\alvr\server\cpp\alvr_server\Statistics.h(51): warning C4244: '=': conversion from 'double' to 'uint64_t', possible loss of data
  cpp\alvr_server\alvr_server.cpp(108): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  cpp\alvr_server\alvr_server.cpp(111): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  cpp\alvr_server\alvr_server.cpp(128): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  cpp\alvr_server\alvr_server.cpp(267): warning C4244: 'return': conversion from 'double' to 'unsigned __int64', possible loss of data
  exit code: 2
  C:\Users\85463\OneDrive\Desktop\vrdecode\alvr2\ALVR\alvr\server\cpp\platform\win32\amf\common\../include/core/Platform.h(394): warning C4201: nonstandard extension used: nameless struct/union
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "cpp/openvr/headers" "-I" "cpp" "-W4" "/std:c++17" "/permissive-" "-DNOMINMAX" "-D_WINSOCKAPI_" "-D_MBCS" "-D_MT" "-FoC:\\Users\\85463\\OneDrive\\Desktop\\vrdecode\\alvr2\\ALVR\\target\\release\\build\\alvr_server-36bb51e4fcde8315\\out\\cpp/platform/win32\\d3d-render-utils\\RenderUtils.o" "-c" "cpp/platform/win32\\d3d-render-utils\\RenderUtils.cpp"
  exit code: 0
  RenderUtils.cpp
  cpp\alvr_server\OvrHMD.cpp(57): warning C4305: '=': truncation from 'double' to 'float'
  exit code: 0
  cpp\alvr_server\OvrHMD.cpp(359): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
  cpp\alvr_server\OvrHMD.cpp(394): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  cpp\alvr_server\OvrHMD.cpp(396): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(752): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(726): note: see reference to function template instantiation 'amf::AMFIOCapsImpl::MemoryType *std::vector<amf::AMFIOCapsImpl::MemoryType,std::allocator<amf::AMFIOCapsImpl::MemoryType>>::_Emplace_reallocate<_Ty>(amf::AMFIOCapsImpl::MemoryType *const ,_Ty &&)' being compiled
          with
          [
              _Ty=amf::AMFIOCapsImpl::MemoryType
          ]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(734): note: see reference to function template instantiation 'amf::AMFIOCapsImpl::MemoryType *std::vector<amf::AMFIOCapsImpl::MemoryType,std::allocator<amf::AMFIOCapsImpl::MemoryType>>::_Emplace_reallocate<_Ty>(amf::AMFIOCapsImpl::MemoryType *const ,_Ty &&)' being compiled
          with
          [
              _Ty=amf::AMFIOCapsImpl::MemoryType
          ]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(748): note: see reference to function template instantiation '_Ty &std::vector<_Ty,std::allocator<_Ty>>::emplace_back<amf::AMFIOCapsImpl::MemoryType>(amf::AMFIOCapsImpl::MemoryType &&)' being compiled
          with
          [
              _Ty=amf::AMFIOCapsImpl::MemoryType
          ]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(746): note: while compiling class template member function 'void std::vector<amf::AMFIOCapsImpl::MemoryType,std::allocator<amf::AMFIOCapsImpl::MemoryType>>::push_back(_Ty &&)'
          with
          [
              _Ty=amf::AMFIOCapsImpl::MemoryType
          ]
  cpp/platform/win32\amf\common\IOCapsImpl.cpp(134): note: see reference to function template instantiation 'void std::vector<amf::AMFIOCapsImpl::MemoryType,std::allocator<amf::AMFIOCapsImpl::MemoryType>>::push_back(_Ty &&)' being compiled
          with
          [
              _Ty=amf::AMFIOCapsImpl::MemoryType
          ]
  C:\Users\85463\OneDrive\Desktop\vrdecode\alvr2\ALVR\alvr\server\cpp\platform\win32\amf\common\IOCapsImpl.h(129): note: see reference to class template instantiation 'std::vector<amf::AMFIOCapsImpl::MemoryType,std::allocator<amf::AMFIOCapsImpl::MemoryType>>' being compiled
  exit code: 2
  exit code: 0
  exit code: 0
  exit code: 0
  exit code: 2
  exit code: 0
  exit code: 0
  exit code: 0
  exit code: 0
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1983): error C2027: use of undefined type 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1806): note: see declaration of 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(2138): note: see reference to class template instantiation 'Microsoft::WRL::Details::RuntimeClassImpl<RuntimeClassFlagsT,true,true,false,I0,TInterfaces...>' being compiled
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(2001): error C2027: use of undefined type 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1806): note: see declaration of 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(2021): error C2027: use of undefined type 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1806): note: see declaration of 'Microsoft::WRL::Details::WeakReferenceImpl'
  exit code: 0
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1983): error C2027: use of undefined type 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1806): note: see declaration of 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(2138): note: see reference to class template instantiation 'Microsoft::WRL::Details::RuntimeClassImpl<RuntimeClassFlagsT,true,true,false,I0,TInterfaces...>' being compiled
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(2001): error C2027: use of undefined type 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1806): note: see declaration of 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(2021): error C2027: use of undefined type 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1806): note: see declaration of 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1401): error C2039: 'CheckForDuplicateEntries': is not a member of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1367): note: see declaration of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1514): note: see reference to class template instantiation 'Microsoft::WRL::Module<Microsoft::WRL::InProc,ModuleT>' being compiled
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1407): error C2039: 'CheckForDuplicateEntries': is not a member of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1367): note: see declaration of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\event.h(316): error C7510: 'Callback': use of dependent template name must be prefixed with 'template'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\event.h(324): error C7510: 'Callback': use of dependent template name must be prefixed with 'template'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1401): error C2039: 'CheckForDuplicateEntries': is not a member of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1367): note: see declaration of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1514): note: see reference to class template instantiation 'Microsoft::WRL::Module<Microsoft::WRL::InProc,ModuleT>' being compiled
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1407): error C2039: 'CheckForDuplicateEntries': is not a member of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1367): note: see declaration of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\event.h(316): error C7510: 'Callback': use of dependent template name must be prefixed with 'template'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\event.h(324): error C7510: 'Callback': use of dependent template name must be prefixed with 'template'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1983): error C2027: use of undefined type 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1806): note: see declaration of 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(2138): note: see reference to class template instantiation 'Microsoft::WRL::Details::RuntimeClassImpl<RuntimeClassFlagsT,true,true,false,I0,TInterfaces...>' being compiled
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(2001): error C2027: use of undefined type 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1806): note: see declaration of 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(2021): error C2027: use of undefined type 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\implements.h(1806): note: see declaration of 'Microsoft::WRL::Details::WeakReferenceImpl'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1401): error C2039: 'CheckForDuplicateEntries': is not a member of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1367): note: see declaration of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1514): note: see reference to class template instantiation 'Microsoft::WRL::Module<Microsoft::WRL::InProc,ModuleT>' being compiled
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1407): error C2039: 'CheckForDuplicateEntries': is not a member of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\module.h(1367): note: see declaration of 'Microsoft::WRL::Details'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\event.h(316): error C7510: 'Callback': use of dependent template name must be prefixed with 'template'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt\wrl\event.h(324): error C7510: 'Callback': use of dependent template name must be prefixed with 'template'
  exit code: 2
  exit code: 0
  exit code: 2
  cpp/platform/win32\CEncoder.cpp(32): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
  exit code: 2

  --- stderr


  error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "cpp/openvr/headers" "-I" "cpp" "-W4" "/std:c++17" "/permissive-" "-DNOMINMAX" "-D_WINSOCKAPI_" "-D_MBCS" "-D_MT" "-FoC:\\Users\\85463\\OneDrive\\Desktop\\vrdecode\\alvr2\\ALVR\\target\\release\\build\\alvr_server-36bb51e4fcde8315\\out\\cpp\\alvr_server\\alvr_server.o" "-c" "cpp\\alvr_server\\alvr_server.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).


thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: command exited with non-zero code `cargo build --release`: 101', alvr\xtask\src\build.rs:46:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\alvr_xtask.exe build-server --release` (exit code: 101)
```

**Comment by Damian96gz** [comment]
Here is the backtrace using RUST_BACKTRACE=1:
`stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library\core\src\result.rs:1785
   3: enum$<core::result::Result<tuple$<>,xshell::error::Error>, 1, 18446744073709551615, Err>::unwrap<tuple$<>,xshell::error::Error>
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3\library\core\src\result.rs:1078
   4: alvr_xtask::build::build_server
             at .\alvr\xtask\src\build.rs:44
   5: alvr_xtask::main
             at .\alvr\xtask\src\main.rs:194
   6: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3\library\core\src\ops\function.rs:248`

**Comment by Damian96gz** [comment]
Update VSCode to the newest version solved this problem
