### ISSUE TITLE
[Linux?] BitrateManager-related crashes with recent builds

### ISSUE THREAD

**Issue by galister** [alvr-org/ALVR#1525]
I've been getting these crashes for the last couple of days. These usually happen within a few seconds after the headset connects.

With master, I just get the SteamVR encountered an error pop-up with no logs, but on the dashboard branch i do actually get a panic message that may or may not help.

```
[2023-03-22T11:14:30Z DEBUG alvr_dashboard::data_sources] server event received: Event { timestamp: "12:14:30.844142957", event_type: Log(LogEvent { severity: Error, content: "What happened:
panicked at 'attempt to add with overflow', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/arith.rs:103:45

Backtrace:
   0: alvr_common::logging::set_panic_hook::{{closure}}
             at /data/github.com/ALVR/alvr/common/src/logging.rs:7:13
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
   2: std::panicking::rust_panic_with_hook
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:577:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   7: core::panicking::panic
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:114:5
   8: <u64 as core::ops::arith::Add>::add
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/arith.rs:103:45
   9: <u64 as core::ops::arith::Add<&u64>>::add
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/internal_macros.rs:61:17
  10: <u64 as core::iter::traits::accum::Sum<&u64>>::sum::{{closure}}
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/traits/accum.rs:75:28
  11: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:298:13
  12: core::iter::traits::iterator::Iterator::fold
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/traits/iterator.rs:2438:21
  13: <alloc::collections::vec_deque::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/collections/vec_deque/iter.rs:78:9
  14: <u64 as core::iter::traits::accum::Sum<&u64>>::sum
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/traits/accum.rs:72:17
  15: core::iter::traits::iterator::Iterator::sum
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/traits/iterator.rs:3408:9
  16: alvr_common::average::SlidingWindowAverage<u64>::get_average
             at /data/github.com/ALVR/alvr/common/src/average.rs:50:13
  17: alvr_server::bitrate::BitrateManager::get_encoder_params
             at /data/github.com/ALVR/alvr/server/src/bitrate.rs:135:22
  18: alvr_server::HmdDriverFactory::get_dynamic_encoder_params
             at /data/github.com/ALVR/alvr/server/src/lib.rs:502:9
  19: _ZN8CEncoder3RunEv
             at /data/github.com/ALVR/alvr/server/cpp/platform/linux/CEncoder.cpp:228:35
  20: _ZSt13__invoke_implIvM7CThreadFvvEPS0_JEET_St21__invoke_memfun_derefOT0_OT1_DpOT2_
             at /usr/include/c++/12.2.1/bits/invoke.h:74:46
  21: _ZSt8__invokeIM7CThreadFvvEJPS0_EENSt15__invoke_resultIT_JDpT0_EE4typeEOS5_DpOS6_
             at /usr/include/c++/12.2.1/bits/invoke.h:96:40
  22: _ZNSt6thread8_InvokerISt5tupleIJM7CThreadFvvEPS2_EEE9_M_invokeIJLm0ELm1EEEEvSt12_Index_tupleIJXspT_EEE
             at /usr/include/c++/12.2.1/bits/std_thread.h:258:26
  23: _ZNSt6thread8_InvokerISt5tupleIJM7CThreadFvvEPS2_EEEclEv
             at /usr/include/c++/12.2.1/bits/std_thread.h:265:20
  24: _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJM7CThreadFvvEPS3_EEEEE6_M_runEv
             at /usr/include/c++/12.2.1/bits/std_thread.h:210:20
  25: execute_native_thread_routine
             at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:82:18
  26: <unknown>
  27: <unknown>
" }) }
```

**Comment by zarik5** [comment]
I've never experienced this crash. Did you increase the history size setting? In any case this seems unsafe because it's right on the edge. I will switch u64 averaging to f32.

**Comment by galister** [comment]
Statistics history size? it's on 256.

**Comment by galister** [comment]
i tried to reduce this stats history size to 64. i restarted the entire dashboard, and the value is saved properly in both session.json and on the dash after restart.

however i would expect the statistics graph to have a smaller sliding window now, but it's still displaying multiple seconds in length and scrolling at seemingly the same speed.

also the same crashes are still happening.

**Comment by zarik5** [comment]
Strange. Anyway the statistics history size it's used for internal calculations for statistics and bitrate, not for the dashboard. A smaller size may make the controller prediction less stable and bitrate calculations more jittery. Please revert the value to 256 for now.

**Comment by zarik5** [comment]
I pushed a commit, try now.

**Comment by zarik5** [comment]
oh great!
