### ISSUE TITLE
alyx, fresh nightly: fatal runtime error: failed to initiate panic, error 5 

### ISSUE THREAD

**Issue by mittorn** [alvr-org/ALVR#1556]
## Description
Rust code fails with unknown exception when first time using gloves in HL:A (Russel's room)

It worked normally in 0.20-dev3

**Comment by mittorn** [comment]
```
Thread 1 "Main Thread" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44      pthread_kill.c: Нет такого файла или каталога.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff76b533f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7666982 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7651464 in __GI_abort () at abort.c:79
#4  0x00007fffc3aa87d7 in std::sys::unix::abort_internal ()
   from /mnt/data2/ALVR20/build/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
#5  0x00007fffc3aa213f in rust_panic () from /mnt/data2/ALVR20/build/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
#6  0x00007fffc3aa1f40 in std::panicking::rust_panic_with_hook ()
   from /mnt/data2/ALVR20/build/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
#7  0x00007fffc3aa1c87 in std::panicking::begin_panic_handler::{{closure}} ()
   from /mnt/data2/ALVR20/build/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
#8  0x00007fffc3aa016e in std::sys_common::backtrace::__rust_end_short_backtrace ()
   from /mnt/data2/ALVR20/build/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
#9  0x00007fffc3aa1992 in rust_begin_unwind () from /mnt/data2/ALVR20/build/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
#10 0x00007fffc2bfda33 in core::panicking::panic_fmt () from /mnt/data2/ALVR20/build/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
#11 0x00007fffc2d2c198 in core::panicking::panic_display ()
   from /mnt/data2/ALVR20/build/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
#12 0x00007fffc2d35bad in alvr_server::HmdDriverFactory::haptics_send ()
   from /mnt/data2/ALVR20/build/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
#13 0x00007fffc2e468e3 in DriverProvider::RunFrame() () from /mnt/data2/ALVR20/build/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
#14 0x0000555555652ae8 in CVRServer::RunFrame() ()
#15 0x0000555555653470 in CVRServer::Run() ()
#16 0x00005555556766f0 in RealMain(unsigned int, VRServerArguments_t&) ()
#17 0x00005555555d547d in main ()
```
Rust haptics code seems to be less safe than c++ version :(

**Comment by zarik5** [comment]
Which nightly are you using? Are you compiling it yourself?

**Comment by mittorn** [comment]
It seems to be fixed now, i just missed that commit:

**Comment by zarik5** [comment]
if you are building from your fork, I suggest you to always rebase and not merge or cherry pick commits.

**Comment by mittorn** [comment]
I rebasing it, but not too often because of big number of dependencies. It is a local patch with system button handler and it can be easily updated to upstream, but i have limited internet connection and it is faster to cherry-pick commits sometimes instead of updating crates and rust compiler until major changes are made. Building for android with 1.66.1 is broken now (need to downgrade android-sdk crate), but 1.68 is only packaged in gentoo 2 weeks ago, after i updated ALVR last time. So i rebase local fork on next update cycle, maybe this month
