### ISSUE TITLE
the libalvr_client_core.so built from build-client-lib operate is Unavailable

### ISSUE THREAD

**Issue by comeonwujian** [alvr-org/ALVR#2282]
## Description
libalvr_client_core.so is Unavailable

I build the libalvr_client_core.so this way;
```
cargo xtask prepare-deps --platform android
cargo xtask build-client-lib --release
```
the result is
```
warning: `alvr_client_core` (lib) generated 5 warnings (run `cargo fix --lib -p alvr_client_core` to apply 1 suggestion)
    Finished `release` profile [optimized] target(s) in 47.71s
     Copying libraries to E:\Project\android\Streaming\ALVR-20.0.0\build\alvr_client_core
$ cbindgen --output E:\Project\android\Streaming\ALVR-20.0.0\build\alvr_client_core\alvr_client_core.h
WARN: Skip alvr_client_core::STATISTICS_MANAGER - (not `no_mangle`).
WARN: Skip alvr_client_core::TRACKING_SENDER - (not `no_mangle`).
WARN: Skip alvr_client_core::STATISTICS_SENDER - (not `no_mangle`).
WARN: Skip alvr_client_core::CONTROL_CHANNEL_SENDER - (not `no_mangle`).
WARN: Skip alvr_client_core::DISCONNECT_NOTIFIER - (not `no_mangle`).
WARN: Skip alvr_client_core::EVENT_QUEUE - (not `no_mangle`).
WARN: Skip alvr_client_core::IS_ALIVE - (not `no_mangle`).
WARN: Skip alvr_client_core::IS_RESUMED - (not `no_mangle`).
WARN: Skip alvr_client_core::IS_STREAMING - (not `no_mangle`).
WARN: Skip alvr_client_core::CONNECTION_THREAD - (not `no_mangle`).
WARN: Skip alvr_client_core::NAL_QUEUE - (not `no_mangle`).
WARN: Skip alvr_client_core::HUD_MESSAGE - (not `no_mangle`).
WARN: Skip alvr_client_core::INITIAL_MESSAGE - (not `pub`).
WARN: Skip alvr_client_core::NETWORK_UNREACHABLE_MESSAGE - (not `pub`).
WARN: Skip alvr_client_core::STREAM_STARTING_MESSAGE - (not `pub`).
WARN: Skip alvr_client_core::SERVER_RESTART_MESSAGE - (not `pub`).
WARN: Skip alvr_client_core::SERVER_DISCONNECTED_MESSAGE - (not `pub`).
WARN: Skip alvr_client_core::DISCOVERY_RETRY_PAUSE - (not `pub`).
WARN: Skip alvr_client_core::RETRY_CONNECT_MIN_INTERVAL - (not `pub`).
WARN: Skip alvr_client_core::NETWORK_KEEPALIVE_INTERVAL - (not `pub`).
WARN: Skip alvr_client_core::CONNECTION_RETRY_INTERVAL - (not `pub`).
WARN: Skip alvr_client_core::BATTERY_POLL_INTERVAL - (not `pub`).
WARN: Skip alvr_client_core::DECODER_INIT_CONFIG - (not `no_mangle`).
WARN: Skip alvr_client_core::DECODER_ENQUEUER - (not `no_mangle`).
WARN: Skip alvr_client_core::DECODER_DEQUEUER - (not `no_mangle`).
WARN: Skip alvr_client_core::EXTERNAL_DECODER - (not `no_mangle`).
WARN: Skip alvr_client_core::LOG_REPEAT_TIMEOUT - (not `pub`).
WARN: Skip alvr_client_core::LAST_LOG_EVENT - (not `no_mangle`).
WARN: Skip alvr_client_core::MICROPHONE_PERMISSION - (Unsupported literal expression. Str(LitStr { token: "android.permission.RECORD_AUDIO" }))
WARN: Skip alvr_client_core::WIFI_LOCK - (not `no_mangle`).
WARN: Skip alvr_client_core::HUD_TEXTURE_WIDTH - (not `pub`).
WARN: Skip alvr_client_core::HUD_TEXTURE_HEIGHT - (not `pub`).
WARN: Skip alvr_client_core::FONT_SIZE - (not `pub`).

Done [3m 35s]
```

I used this libalvr_client_core.so from alvr_client_core/arm64-v8a dir in my project,  and link it in the cmakelists.txt like this:
```
add_library(alvr_client_core SHARED IMPORTED)
SET_TARGET_PROPERTIES(alvr_client_core PROPERTIES LINKER_LANGUAGE CXX
        IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/../jniLibs/${CMAKE_ANDROID_ARCH_ABI}/libalvr_client_core.so)
target_link_libraries(alvr_openxr
        # The game activity
        game-activity::game-activity

        # EGL and other dependent libraries required for drawing
        # and interacting with Android system
        EGL
        GLESv3
        jnigraphics
        android
        log
        **alvr_client_core**
        openxr_loader)

```
 and load library in Activity like this:
```
    static {
        System.loadLibrary("alvr_openxr");
        System.loadLibrary("alvr_client_core");
    }

```
**but crash happened，**
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "E:/Project/android/Streaming/Alvr_openxr/app/src/main/cpp/../jniLibs/arm64-v8a/libalvr_client_core.so" not found
05-09 07:26:38.497 17161 17161 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
05-09 07:26:38.497 17161 17161 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
05-09 07:26:38.497 17161 17161 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1667)
```

I have tried other .so file，link it using the same method above，no crash happen.

so can you tell me the reason for this case，thank you very much.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment
android 10

### Hardware
VR device

**Comment by The-personified-devil** [comment]
Have you ensured that you're actually bundling the shared object in the apk?

**Comment by zarik5** [comment]
you're probably missing this in build.gradle:
```
sourceSets {
    main {
        jniLibs.srcDirs = ["../../build/alvr_client_core"]
    }
}
```
Of course you might have to adjust the path

**Comment by comeonwujian** [comment]
> Have you ensured that you're actually bundling the shared object in the apk?

Yes，I have decompressed the apk and can see alvr_content_come.so.

**Comment by comeonwujian** [comment]
> you're probably missing this in build.gradle:
> 
> ```groovy-gradle
> sourceSets {
>     main {
>         jniLibs.srcDirs = ["../../build/alvr_client_core"]
>     }
> }
> ```
> 
> Of course you might have to adjust the path.
> 
> In CMakeLists.txt add:
> 
> ```cmake
> link_directories(../../build/alvr_client_core/${ANDROID_ABI})
> ```
> 
> and remove the asterisks around `alvr_client_core` in `target_link_libraries`

add
` link_directories(../../build/alvr_client_core/${ANDROID_ABI})`
Solved my problem. Thank you very much.
