### ISSUE TITLE
Linux Launcher error: Failed to run eframe: Glutin

### ISSUE THREAD

**Issue by TheLazyHatGuy** [alvr-org/ALVR#2321]
## Description
When I try to run the launcher on Linux, I get the following 
```sh
:~/Downloads/alvr_launcher_linux$ RUST_BACKTRACE=1 ./ALVR\ Launcher 
thread 'main' panicked at alvr/launcher/src/main.rs:76:6:
Failed to run eframe: Glutin(Error { raw_code: Some(2), raw_os_message: Some("BadValue (integer parameter out of range for operation)"), kind: BadAttribute })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::expect
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1034:23
   4: alvr_launcher::main
             at /home/runner/work/ALVR/ALVR/alvr/launcher/src/main.rs:56:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=a8a2ca27f5)

### Installation
**ALVR Version**: 20.9.1

**ALVR Settings File**: n/a

**SteamVR Version**: 2.8.2

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** 
Pop!_OS 22.04 LTS

**Comment by TheLazyHatGuy** [comment]
Turn out there was an issue with a driver version mismatch.
I followed this guide: https://stackoverflow.com/questions/75991865/nvidia-smi-version-mismatch-error-when-i-try-nvidia-smi

**Comment by The-personified-devil** [comment]
shouldn't crash like that regardless

**Comment by zarik5** [comment]
I'm not sure how much we can do about it. it's not our responsibility fixing this bug, but our responsibility should make sure we don't update to a bugged version of egui. Still, driver bugs like these are hard to test for.

**Comment by The-personified-devil** [comment]
I just thought the error seems too cryptic and doesnt clarify that its not an alvr internal issue, but it's probably not feasible to differentiate
