### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: NotPresent

### ISSUE THREAD

**Issue by xDShot** [alvr-org/ALVR#2505]
## Description
Fails to build client on Arch Linux

```
warning: `alvr_xtask` (bin "alvr_xtask") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/alvr_xtask build-client --release`
thread 'main' panicked at alvr/xtask/src/build.rs:395:63:
called `Result::unwrap()` on an `Err` value: NotPresent
stack backtrace:
   0:     0x64a22e5c944a - std::backtrace_rs::backtrace::libunwind::trace::h99efb0985cae5d78
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x64a22e5c944a - std::backtrace_rs::backtrace::trace_unsynchronized::he2c1aa63b3f7fad8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x64a22e5c944a - std::sys::backtrace::_print_fmt::h8a221d40f5e0f88b
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:66:9
   3:     0x64a22e5c944a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:39:26
   4:     0x64a22e5ec87b - core::fmt::rt::Argument::fmt::h5da9c218ec984eaf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/rt.rs:177:76
   5:     0x64a22e5ec87b - core::fmt::write::hf5713710ce10ff22
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/mod.rs:1178:21
   6:     0x64a22e5c6363 - std::io::Write::write_fmt::hda708db57927dacf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/io/mod.rs:1823:15
   7:     0x64a22e5cad92 - std::sys::backtrace::BacktraceLock::print::hbcdbec4d97c91528
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:42:9
   8:     0x64a22e5cad92 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:266:22
   9:     0x64a22e5ca9fe - std::panicking::default_hook::h81c8cd2e7c59ee33
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:293:9
  10:     0x64a22e5cb61f - std::panicking::rust_panic_with_hook::had2118629c312a4a
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:797:13
  11:     0x64a22e5cb307 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:671:13
  12:     0x64a22e5c9929 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:170:18
  13:     0x64a22e5caf94 - rust_begin_unwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
  14:     0x64a22e5045f3 - core::panicking::panic_fmt::h3eea515d05f7a35e
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
  15:     0x64a22e504ac6 - core::result::unwrap_failed::h7c8d8bbbcf45dc13
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1677:5
  16:     0x64a22e5221cd - core::result::Result<T,E>::unwrap::h8432a03bb89035d6
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1102:23
  17:     0x64a22e5221cd - alvr_xtask::build::build_android_client::hfaf8715cffd471cd
                               at /home/xdshot/ALVR/alvr/xtask/src/build.rs:395:41
  18:     0x64a22e52538b - alvr_xtask::main::h907567e94568e5e1
                               at /home/xdshot/ALVR/alvr/xtask/src/main.rs:207:35
  19:     0x64a22e5106fb - core::ops::function::FnOnce::call_once::h2a1c75cda645c5da
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
  20:     0x64a22e5195ee - std::sys::backtrace::__rust_begin_short_backtrace::h44f5476360f9a2a1
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:154:18
  21:     0x64a22e518271 - std::rt::lang_start::{{closure}}::hf76e73677d4b9596
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:164:18
  22:     0x64a22e5c14b0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h08ecba131ab90ec4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:284:13
  23:     0x64a22e5c14b0 - std::panicking::try::do_call::hf33a59fd8ce953f4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  24:     0x64a22e5c14b0 - std::panicking::try::h5005ce80ce949fd8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  25:     0x64a22e5c14b0 - std::panic::catch_unwind::hfbae19e2e2c5b7ed
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  26:     0x64a22e5c14b0 - std::rt::lang_start_internal::{{closure}}::ha0331c3690741813
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:48
  27:     0x64a22e5c14b0 - std::panicking::try::do_call::hcdcbdb616b4d0295
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  28:     0x64a22e5c14b0 - std::panicking::try::h3f2f1725a07d2256
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  29:     0x64a22e5c14b0 - std::panic::catch_unwind::h51869e04b56b2dc3
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  30:     0x64a22e5c14b0 - std::rt::lang_start_internal::h4d90db0530245041
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:20
  31:     0x64a22e51824a - std::rt::lang_start::ha166ecfbb61ab0c2
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:163:17
  32:     0x64a22e52623e - main
  33:     0x7560ce30be08 - <unknown>
  34:     0x7560ce30becc - __libc_start_main
  35:     0x64a22e504e85 - _start
  36:                0x0 - <unknown>
  ```

**Comment by The-personified-devil** [comment]
You need to actually follow the build process and run `prepare-deps` first

**Comment by xDShot** [comment]
> You need to actually follow the build process and run `prepare-deps` first

I did. These are commands I use:

```sh
cargo xtask prepare-deps --no-nvidia
cargo xtask build-streamer --release
cargo xtask prepare-deps --platform android
cargo xtask build-client --release
```

**Comment by The-personified-devil** [comment]
What version are you trying to compile?

**Comment by xDShot** [comment]
> What version are you trying to compile?

Latest commit currently. Also tried [v20.11.1](https://github.com/alvr-org/ALVR/releases/tag/v20.11.1), [v20.11.0](https://github.com/alvr-org/ALVR/releases/tag/v20.11.0), same result

**Comment by xDShot** [comment]
> JAVA_HOME

That was it 👍 Strangely it's gone, had to add explicitly
