### ISSUE TITLE
build-android-deps error

### ISSUE THREAD

**Issue by x081x** [alvr-org/ALVR#740]
When I build alvr client(ALVR-15.2.1), there was a error. I read the guide, but I don't find the android-deps.zip.

here is cmd output: 
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.9.4
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>cd F:\Workspace\Projects\ALVR-15.2.1

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>f:

F:\Workspace\Projects\ALVR-15.2.1>
F:\Workspace\Projects\ALVR-15.2.1>
F:\Workspace\Projects\ALVR-15.2.1>cargo xtask build-android-deps
   Compiling cc v1.0.67
   Compiling autocfg v1.0.1
   Compiling winapi v0.3.9
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.94
   Compiling adler v1.0.2
   Compiling proc-macro2 v1.0.26
   Compiling memchr v2.3.4
   Compiling unicode-xid v0.2.1
   Compiling spin v0.5.2
   Compiling untrusted v0.7.1
   Compiling matches v0.1.8
   Compiling gimli v0.23.0
   Compiling syn v1.0.71
   Compiling tinyvec_macros v0.1.0
   Compiling getrandom v0.2.2
   Compiling pkg-config v0.3.19
   Compiling log v0.4.14
   Compiling rustc-demangle v0.1.18
   Compiling object v0.23.0
   Compiling crc32fast v1.2.1
   Compiling ucd-trie v0.1.3
   Compiling byteorder v1.4.3
   Compiling percent-encoding v2.1.0
   Compiling void v1.0.2
   Compiling ascii v0.9.3
   Compiling either v1.6.1
   Compiling ppv-lite86 v0.2.10
   Compiling base64 v0.13.0
   Compiling alvr_xtask v1.0.0 (F:\Workspace\Projects\ALVR-15.2.1\alvr\xtask)
   Compiling once_cell v1.7.2
   Compiling regex-syntax v0.6.23
   Compiling linked-hash-map v0.5.4
   Compiling chunked_transfer v1.4.0
   Compiling pico-args v0.4.0
   Compiling fs_extra v1.2.0
   Compiling lazy_static v1.4.0
   Compiling miniz_oxide v0.4.4
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling unicode-bidi v0.3.5
   Compiling tinyvec v1.2.0
   Compiling pest v2.1.3
   Compiling form_urlencoded v1.0.1
   Compiling unreachable v1.0.0
   Compiling ring v0.16.20
   Compiling backtrace v0.3.58
   Compiling bzip2-sys v0.1.10+1.0.8
   Compiling runas v0.2.1
   Compiling addr2line v0.14.1
   Compiling unicode-normalization v0.1.17
   Compiling semver-parser v0.10.2
   Compiling combine v3.8.1
   Compiling aho-corasick v0.7.15
   Compiling rand_core v0.6.2
   Compiling quote v1.0.9
   Compiling idna v0.2.3
   Compiling semver v0.11.0
   Compiling rand_chacha v0.3.0
   Compiling regex v1.4.6
   Compiling flate2 v1.0.20
   Compiling url v2.2.1
   Compiling rand v0.8.3
   Compiling time v0.1.43
   Compiling winapi-util v0.1.5
   Compiling dirs-sys v0.3.6
   Compiling failure v0.1.8
   Compiling chrono v0.4.19
   Compiling same-file v1.0.6
   Compiling dirs v3.0.2
   Compiling walkdir v2.3.2
   Compiling bzip2 v0.3.3
   Compiling which v3.1.1
   Compiling toml_edit v0.2.0
   Compiling webpki v0.21.4
   Compiling sct v0.6.1
   Compiling webpki-roots v0.21.1
   Compiling rustls v0.19.1
   Compiling thiserror-impl v1.0.24
   Compiling thiserror v1.0.24
   Compiling zip v0.5.12
   Compiling ureq v2.1.1
    Finished dev [unoptimized + debuginfo] target(s) in 1m 17s
     Running `target\debug\alvr_xtask.exe build-android-deps`

> rustup target add aarch64-linux-android
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
Downloading Rust Android Gradle plugin...
Extracting Rust Android Gradle plugin into C:\Users\WORKER\AppData\Local\Temp\Js7EYQ9UtF...

> C:\Users\WORKER\AppData\Local\Temp\Js7EYQ9UtF\rust-android-gradle-6e553c13ef2d9bb40b58a7675b96e0757d1b0443\gradlew.bat publish
Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip

Exception in thread "main" javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1958)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1915)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1898)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1419)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1396)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
        at sun.security.validator.Validator.getInstance(Validator.java:179)
        at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1508)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:215)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1024)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:954)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1065)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1384)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1412)
        ... 14 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
        at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
        ... 26 more
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Command failed: "', alvr\xtask\src\dependencies.rs:64:6
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\core\src\panicking.rs:92
   2: core::result::unwrap_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\core\src\result.rs:1355
   3: core::result::Result<tuple<>, alloc::boxed::Box<Error, alloc::alloc::Global>>::unwrap<tuple<>,alloc::boxed::Box<Error, alloc::alloc::Global>>
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\library\core\src\result.rs:1037
   4: alvr_xtask::dependencies::build_rust_android_gradle
             at .\alvr\xtask\src\dependencies.rs:60
   5: alvr_xtask::dependencies::build_deps
             at .\alvr\xtask\src\dependencies.rs:197
   6: alvr_xtask::main
             at .\alvr\xtask\src\main.rs:489
   7: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\alvr_xtask.exe build-android-deps` (exit code: 101)

**Comment by x081x** [comment]
reinstall jdk
