### ISSUE TITLE
Compilation ALVR failed with error [thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Command failed: "', alvr/xtask/src/main.rs:206:10]

### ISSUE THREAD

**Issue by NTMan** [alvr-org/ALVR#830]
Compilation ALVR failed with error:
```
  --- stderr
  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I/usr/include/ffmpeg" "-I" "cpp/openvr/headers" "-I" "cpp" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/builddir/build/BUILD/ALVR-16.0.0/target/release/build/alvr_server-9b0f829170f8a9d5/out/cpp/platform/linux/ffmpeg_helper.o" "-c" "cpp/platform/linux/ffmpeg_helper.cpp" with args "c++" did not execute successfully (status code exit status: 1).
warning: build failed, waiting for other jobs to finish...
error: build failed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Command failed: "', alvr/xtask/src/main.rs:206:10
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /builddir/build/BUILD/rustc-1.55.0-src/library/core/src/result.rs:1281:23
   4: alvr_xtask::build_server
             at ./alvr/xtask/src/main.rs:198:9
   5: alvr_xtask::main
             at ./alvr/xtask/src/main.rs:567:35
   6: core::ops::function::FnOnce::call_once
             at /builddir/build/BUILD/rustc-1.55.0-src/library/core/src/ops/function.rs:227:5
```

[build.log](https://github.com/alvr-org/ALVR/files/7358372/build.log)

**Comment by NTMan** [comment]
As far as I understand, no one here is interested in version [16.0.0](https://github.com/alvr-org/ALVR/archive/refs/tags/v16.0.0.tar.gz) being built on Linux. The nightly build building successfully but nightly build has another [issues](https://github.com/alvr-org/ALVR/issues/849).

Build logs:
[root.log](https://github.com/alvr-org/ALVR/files/7616895/root.log)
[build.log](https://github.com/alvr-org/ALVR/files/7616894/build.log)
