### ISSUE TITLE
Build server error linux

### ISSUE THREAD

**Issue by Naia-love** [alvr-org/ALVR#890]
So alvr wasnt working and was giving me something like `failed to create VAAPI encoder`, after looking at the issue here i found [this](https://github.com/alvr-org/ALVR/issues/742#issuecomment-885289000) and so wanted to try building alvr myself with this patch

but
`cargo xtask build-server --nightly` give me:

```
The following warnings were emitted during compilation:

warning: cpp/platform/linux/EncodePipelineSW.cpp: In constructor 'alvr::EncodePipelineSW::EncodePipelineSW(std::vector<alvr::VkFrame>&, alvr::VkFrameCtx&)':
warning: cpp/platform/linux/EncodePipelineSW.cpp:44:56: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
warning:    44 |   AVCodec *codec = AVCODEC.avcodec_find_encoder_by_name(encoder_name);
warning: cpp/platform/linux/EncodePipelineVAAPI.cpp: In constructor 'alvr::EncodePipelineVAAPI::EncodePipelineVAAPI(std::vector<alvr::VkFrame>&, alvr::VkFrameCtx&)':
warning: cpp/platform/linux/EncodePipelineVAAPI.cpp:117:56: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
warning:   117 |   AVCodec *codec = AVCODEC.avcodec_find_encoder_by_name(encoder_name);

error: failed to run custom build command for `alvr_server v16.0.0+nightly.2021.12.25 (/home/naia/ALVR/alvr/server)`

Caused by:
  process didn't exit successfully: `/home/naia/ALVR/target/debug/build/alvr_server-b98fed6c695bbede/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/ALVR-common/reedsolomon/rs.o" "-c" "cpp/ALVR-common/reedsolomon/rs.c"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/ALVR-common/common-utils.o" "-c" "cpp/ALVR-common/common-utils.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/ALVR-common/exception.o" "-c" "cpp/ALVR-common/exception.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/OvrHMD.o" "-c" "cpp/alvr_server/OvrHMD.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/Settings.o" "-c" "cpp/alvr_server/Settings.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/ClientConnection.o" "-c" "cpp/alvr_server/ClientConnection.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/Utils.o" "-c" "cpp/alvr_server/Utils.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/alvr_server.o" "-c" "cpp/alvr_server/alvr_server.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/IDRScheduler.o" "-c" "cpp/alvr_server/IDRScheduler.cpp"
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/ChaperoneUpdater.o" "-c" "cpp/alvr_server/ChaperoneUpdater.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/VSyncThread.o" "-c" "cpp/alvr_server/VSyncThread.cpp"
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/OvrDisplayComponent.o" "-c" "cpp/alvr_server/OvrDisplayComponent.cpp"
  exit status: 0
  exit status: 0
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/driverlog.o" "-c" "cpp/alvr_server/driverlog.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/PoseHistory.o" "-c" "cpp/alvr_server/PoseHistory.cpp"
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/OvrController.o" "-c" "cpp/alvr_server/OvrController.cpp"
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/OvrViveTrackerProxy.o" "-c" "cpp/alvr_server/OvrViveTrackerProxy.cpp"
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/alvr_server/Logger.o" "-c" "cpp/alvr_server/Logger.cpp"
  exit status: 0
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/shared/threadtools.o" "-c" "cpp/shared/threadtools.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/platform/linux/ffmpeg_helper.o" "-c" "cpp/platform/linux/ffmpeg_helper.cpp"
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/platform/linux/EncodePipelineSW.o" "-c" "cpp/platform/linux/EncodePipelineSW.cpp"
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/platform/linux/generated/avfilter_loader.o" "-c" "cpp/platform/linux/generated/avfilter_loader.cpp"
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/platform/linux/generated/avutil_loader.o" "-c" "cpp/platform/linux/generated/avutil_loader.cpp"
  exit status: 0
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/platform/linux/generated/avcodec_loader.o" "-c" "cpp/platform/linux/generated/avcodec_loader.cpp"
  exit status: 0
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/platform/linux/generated/swscale_loader.o" "-c" "cpp/platform/linux/generated/swscale_loader.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/platform/linux/CEncoder.o" "-c" "cpp/platform/linux/CEncoder.cpp"
  exit status: 0
  exit status: 0
  exit status: 0
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/platform/linux/EncodePipelineVAAPI.o" "-c" "cpp/platform/linux/EncodePipelineVAAPI.cpp"
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/platform/linux/EncodePipeline.o" "-c" "cpp/platform/linux/EncodePipeline.cpp"
  exit status: 0
  exit status: 0
  cargo:warning=cpp/platform/linux/EncodePipelineSW.cpp: In constructor 'alvr::EncodePipelineSW::EncodePipelineSW(std::vector<alvr::VkFrame>&, alvr::VkFrameCtx&)':
  cargo:warning=cpp/platform/linux/EncodePipelineSW.cpp:44:56: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  cargo:warning=   44 |   AVCodec *codec = AVCODEC.avcodec_find_encoder_by_name(encoder_name);
  exit status: 1
  cargo:warning=cpp/platform/linux/EncodePipelineVAAPI.cpp: In constructor 'alvr::EncodePipelineVAAPI::EncodePipelineVAAPI(std::vector<alvr::VkFrame>&, alvr::VkFrameCtx&)':
  cargo:warning=cpp/platform/linux/EncodePipelineVAAPI.cpp:117:56: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  cargo:warning=  117 |   AVCodec *codec = AVCODEC.avcodec_find_encoder_by_name(encoder_name);
  exit status: 1
  exit status: 0
  exit status: 0
  exit status: 0

  --- stderr


  error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-o" "/home/naia/ALVR/target/debug/build/alvr_server-d33f263a0ffe9e83/out/cpp/platform/linux/EncodePipelineSW.o" "-c" "cpp/platform/linux/EncodePipelineSW.cpp" with args "c++" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
error: build failed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StringError("Command failed: ")', alvr/xtask/src/main.rs:155:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
   4: alvr_xtask::build_server
             at ./alvr/xtask/src/main.rs:147:5
   5: alvr_xtask::main
             at ./alvr/xtask/src/main.rs:365:35
   6: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

if also tried building without the patch and it give me the same error ^^;
so halp pls (or if you know how to make it work on nvidia gpu without needing to build it ^^)

I'm on Void Linux 5.15.7_1

**Comment by Naia-love** [comment]
I tried to checkout on 16.0.0-rc2, 16.0.0. too, and i get the same error. So im guessing i have a lib in the wrong versions or missing one or sum, sorry ^^; 
(i do have libavcodec, or just all ffmpeg libs, and void ffmpeg is built with vulkan support)

**Comment by bugs181** [comment]
My issue looks to be related (looks very similar to your compile output)

```bash
WARNING: Disabled h264_vaapi_encoder because some selected dependency is unsatisfied: cbs_h264 vaapi_encode
WARNING: Disabled hevc_vaapi_encoder because some selected dependency is unsatisfied: cbs_h265 vaapi_encode
WARNING: Disabled h264_vaapi_hwaccel because not all dependencies are satisfied: vaapi
WARNING: Disabled hevc_vaapi_hwaccel because not all dependencies are satisfied: vaapi VAPictureParameterBufferHEVC
WARNING: Disabled scale_vaapi_filter because not all dependencies are satisfied: vaapi
```
and later

```bash
cargo build --release  --no-default-features --features default
    Finished release [optimized] target(s) in 0.09s
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "No such file or directory (os error 2)" }', alvr/xtask/src/main.rs:210:82
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
   4: alvr_xtask::build_server
             at ./alvr/xtask/src/main.rs:210:9
   5: alvr_xtask::main
             at ./alvr/xtask/src/main.rs:365:35
   6: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

System specs are:
CPU: 11th Gen Intel® Core™ i7-11800H @ 2.30GHz × 16 
GPU: NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q 8GB/16GB] / NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2
RAM: 64GB

How do we fix this?

**Comment by stefnn** [comment]
was just running into the same problem, seems to be a update in ffmpeg 5.0 (namely https://github.com/FFmpeg/FFmpeg/commit/626535f6a169e2d821b969e0ea77125ba7482113)  which switched to const values.

For now using ffmpeg 4.4.1 or changing the code to const AVCodec* should solve the problem

**Comment by Naia-love** [comment]
oh okay thanks I'll try ^^
if you have a patch file or can be more precise about what need to be changed please, not sure i understand sorry-

**Comment by stefnn** [comment]
right now i simply downgraded ffmpeg to version 4.4.1 

(but i assume in order to fix the code all places like
`AVCodec *codec = AVCODEC.avcodec_find_encoder_by_name(encoder_name);`
need to be changed to 
`const AVCodec *codec = AVCODEC.avcodec_find_encoder_by_name(encoder_name);`

**Comment by Naia-love** [comment]
just realised, but I _have_ ffmpeg 4.4.1!
No idea what is happening, it is afaik the only ffmpeg i have on my machine (well according to `where` at least)
but modifying the lines you said seems to work? at least it build ? x)

**Comment by Naia-love** [comment]
It worked
